# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/176vDkAkSK_LmtZ6TDVRbqTM0Ob-PrvQv
"""

print("Welcome to python world! Let's start coding")